const bancos = {
  "011": "Banco de la Nación Argentina",
  "014": "Banco de la Provincia de Buenos Aires",
  "017": "Banco de la Provincia de Córdoba",
  "019": "Banco de la Provincia de Santa Fe",
  "027": "Banco Supervielle S.A.",
  "029": "Banco de la Ciudad de Buenos Aires",
  "034": "Banco Patagonia S.A.",
  "044": "Banco Hipotecario S.A.",
  "047": "Banco de Galicia y Buenos Aires S.A.",
  "072": "Banco Santander Río S.A.",
  "083": "Banco del Chubut S.A.",
  "100": "Banco Macro S.A.",
  "102": "Banco de la Provincia de Tucumán",
  "147": "Banco B.I. Creditanstalt S.A.",
  "150": "HSBC Bank Argentina S.A.",
  "178": "Banco de la Provincia de Mendoza",
  "191": "Banco de la Provincia de Jujuy",
  "206": "Banco Comafi S.A.",
  "208": "Banco de Servicios y Transacciones S.A.",
  "220": "Banco Nación Argentina (Sucursal específica)",
  "224": "Banco de Corrientes S.A.",
  "259": "Banco Itaú Argentina S.A.",
  "285": "Banco Macro S.A.",
  "292": "Banco Credicoop Cooperativo Ltdo."
};

